// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2E44YwqoryRB4kKCAApUCV02PW1Catcc',
    appId: '1:509890937344:web:44830cbd17ae2da5a24ee5',
    messagingSenderId: '509890937344',
    projectId: 'dollcalculater',
    authDomain: 'dollcalculater.firebaseapp.com',
    storageBucket: 'dollcalculater.appspot.com',
    measurementId: 'G-7MCYNELYHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbQxNVJO2yD9U3ROdKtHPg0YIK_wNuF-Q',
    appId: '1:509890937344:android:1d4dab162c673c90a24ee5',
    messagingSenderId: '509890937344',
    projectId: 'dollcalculater',
    storageBucket: 'dollcalculater.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArLNtv_qMypyCdH3sSVaye1e1_0L3AfYc',
    appId: '1:509890937344:ios:f165eb7182de7b6fa24ee5',
    messagingSenderId: '509890937344',
    projectId: 'dollcalculater',
    storageBucket: 'dollcalculater.appspot.com',
    iosClientId: '509890937344-b83qt2qdrgaf0bnptriscpss0qtpcfht.apps.googleusercontent.com',
    iosBundleId: 'com.example.dollApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArLNtv_qMypyCdH3sSVaye1e1_0L3AfYc',
    appId: '1:509890937344:ios:f165eb7182de7b6fa24ee5',
    messagingSenderId: '509890937344',
    projectId: 'dollcalculater',
    storageBucket: 'dollcalculater.appspot.com',
    iosClientId: '509890937344-b83qt2qdrgaf0bnptriscpss0qtpcfht.apps.googleusercontent.com',
    iosBundleId: 'com.example.dollApp',
  );
}
